---
# The connection information for the src database.
source_connection: dbname=postgres
source_connection_for_replication: dbname=postgres replication=database

# Table name to replicate.
source_table_name: yolos
source_schema_name: public

# The connection information for the dest database.
destination_connection: dbname=postgres user=remote_admin password=remote_admin host=localhost port=6432

# Table name to receive data. NOTE: Leave blank to keep the same as source.
destination_table_name: yolos
destination_schema_name: public

# The name of the publication on the src database that includes the
# source table and schema. Without this, we'll receive no new changes.
# You can leave this blank to create a new publication scoped to the
# table specified in this config.
publication_name: pub_on_yolos

# Specify the name of the replication slot. Leave blank for random.
replication_slot_name: ""
# Continue replicating after the post-copy checkpoint LSN has been reached.
replication_continue_after_copy_checkpoint: false
# Should the replication slot only exist for the life of the process.
replication_slot_is_temporary: true
# Skip the creation of the replication slot, ex: using an existing replication slot.
replication_slot_skip_create: false

# Parameters for the batch copying.
# ID range to walk when using id range mode.
copy_batch_size: 100000

# Number of workers to run in parllel. Don't kill your database.
copy_worker_count: 10

# Set to "true" to have pghost mimick traditional logical replication by
# exporing a transaction snapshot used by all copy workers.
copy_use_transaction_snapshot: true

# Use keyset pagination for more precise data ranges.
# Warning: This is slow for really large tables but still might be
# worth it.
copy_use_keyset_pagination: true